Repository ucsb-cs156-f24/proj-happycows-f24-11, pull requests merged in 2024-11, with the labels that each got.

#19 Minor UX Fix: Make explanation of buying and selling cows neater
  frontend/src/main/components/Commons/ManageCows.js
Labels: 5, Merge Candidate-CI

#14 MINOR BUG FIX: Correct "Mattanjah de Vries" link
  frontend/src/main/components/Nav/Footer.js
Labels: 5

#24 Hide previous and next buttons for Profit Table
  frontend/package.json
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
Labels: 10, Merge Candidate-CI

#23 Wrap totalwealth value with USD.parse [ISSUE #7]
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
Labels: 5, Merge Candidate-CI

#27 Added Frontend Table Component for GET/Read Operations for Announcements
  frontend/src/main/pages/AdminAnnouncementsPage.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 10, Merge Candidate-CI

#28 Created Postgres table json config, entity and repository for Students Table
  src/main/java/edu/ucsb/cs156/happiercows/entities/Student.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/StudentRepository.java
  src/main/resources/db/migration/changes/StudentTable.json
Labels: 5, Merge Candidate-CI

#29 fix width
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
Labels: 5, Merge Candidate-CI

#38 ALL CRUD operations for courses (admin only)
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Courses.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CoursesRepository.java
  src/main/resources/db/migration/changes/Courses.json
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelperTests.java
  src/test/java/edu/ucsb/cs156/happiercows/helpers/ReportCSVHelperTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobIndTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobIndTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: 10, Merge Candidate-CI

#31 Added Post Endpoint for single record in students table
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Courses.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentControllerTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#54 Student Delete Endpoint
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentControllerTests.java
Labels: 10, Ready-For-Staff

#40 GetAllByCourseId Endpoint added — GET endpoint for multiple students objects in table
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/StudentRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentControllerTests.java
Labels: 10, Merge Candidate-CI

#50 (MERGE PR #38 BEFORE TOUCHING THIS) Form Component for Courses plus test, Create fixtures for Courses (
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/stories/components/Courses/CoursesForm.stories.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#53 Added Frontend Delete Button Component and Modal Component for DELETE Operation for Announcements
  frontend/src/main/components/Announcement/AnnouncementTable.js
  frontend/src/main/pages/AdminAnnouncementsPage.js
  frontend/src/main/utils/announcementUtils.js
  frontend/src/tests/components/Announcement/AnnouncementsTable.test.js
  frontend/src/tests/utils/announcementUtils.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 10, Merge Candidate-CI

#51 (MERGE PR #50 BEFORE TOUCHING THIS) Table Component for Courses plus tests
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/utils/coursesUtils.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/utils/coursesUtils.test.js
Labels: 10
